### ISSUE TITLE
基本となるCSSの作成

### ISSUE THREAD

**Issue by Dai-H15** [Naka-Home/team-project#2]
統一感を出すためにフォントサイズ・リストのボーダーの色・各タグのマージン等を話し合いで決め、それぞれのサイトに適用されるようにする

**Comment by Naka-Home** [comment]
ひとまずindex.cssの背景などだけ決めてしまいましょう。
引き続きお願いします。

**Comment by Dai-H15** [comment]
了解です！

**Comment by Naka-Home** [comment]
indexや個人ページの背景設定は終わりましたので、
クローズしておきます。
